// packages/presets/templates/pingcrm/vue-ts/resources/components/file-input.vue
<script setup lang="ts">
import { type PropType, ref, watch } from 'vue'

const props = defineProps({
  modelValue: File as PropType<File | null>,
  label: String,
  accept: String,
  errors: {
    type: Array,
    default: () => [],
  },
})

const emit = defineEmits(['update:modelValue'])

const fileRef = ref<HTMLInputElement | null>(null)

watch(() => props.modelValue, (value) => {
  if (!value) {
    fileRef.value!.value = ''
  }
})

const filesize = (size: number) => {
  var i = Math.floor(Math.log(size) / Math.log(1024))
  return (size / Math.pow(1024, i)).toFixed(2) + ' ' + ['B', 'kB', 'MB', 'GB', 'TB'][i]
}

const browse = () => {
  fileRef.value?.click()
}
const change = (e: Event) => {
  emit('update:modelValue', (e.target as HTMLInputElement).files?.[0])
}
const remove = () => {
  emit('update:modelValue', null)
}

defineExpose({ browse, change, remove })
</script>

<template>
  <div>
    <label v-if="label" class="form-label">{{ label }}:</label>
    <div class="form-input p-0" :class="{ error: errors.length }">
      <input ref="fileRef" type="file" :accept="accept" class="hidden" @change="change" />
      <div v-if="!modelValue" class="p-2">
        <button type="button" class="px-4 py-1 text-white text-xs font-medium bg-gray-500 hover:bg-gray-700 rounded-sm"
          @click="browse">Browse</button>
      </div>
      <div v-else class="flex items-center justify-between p-2">
        <div class="flex-1 pr-1">
          {{ modelValue.name }} <span class="text-gray-500 text-xs">({{ filesize(modelValue.size) }})</span>
        </div>
        <button type="button" class="px-4 py-1 text-white text-xs font-medium bg-gray-500 hover:bg-gray-700 rounded-sm"
          @click="remove">Remove</button>
      </div>
    </div>
    <div v-if="errors.length" class="form-error">{{ errors[0] }}</div>
  </div>
</template>

// packages/presets/templates/pingcrm/react/resources/components/file-input.tsx
// @ts-nocheck
import {
  type ComponentProps,
  type ComponentPropsWithRef,
  type FormEvent,
  createRef,
  useState,
} from 'react'

export interface ButtonProps extends ComponentProps<'button'> {
  text: string
}

const Button = ({ text, onClick }: ButtonProps) => (
  <button
    type="button"
    className="px-4 py-1 text-white text-xs font-medium bg-gray-600 hover:bg-gray-700 rounded-sm focus:outline-none"
    onClick={onClick}
  >
    {text}
  </button>
)

export interface FileInputProps
  extends Omit<ComponentPropsWithRef<'input'>, 'onInput'> {
  label: string
  error?: string
  onInput: (photo: File) => void
}

export default function FileInput({
  className,
  name,
  label,
  accept,
  error,
  onInput,
}: FileInputProps) {
  const fileRef = createRef<HTMLInputElement>()
  const [file, setFile] = useState<File | null>(null)

  const filesize = (size: number) => {
    var i = Math.floor(Math.log(size) / Math.log(1024))
    return (
      (size / Math.pow(1024, i)).toFixed(2) +
      ' ' +
      ['B', 'kB', 'MB', 'GB', 'TB'][i]
    )
  }

  const browse = () => {
    if (fileRef) {
      fileRef.current?.click()
    }
  }

  const handleFileChange = (e: FormEvent<HTMLInputElement>) => {
    const input = e.target as HTMLInputElement

    if (!input.files?.length) {
      return
    }

    const file = input.files[0]

    setFile(file)
    onInput(file)
  }

  const remove = () => {
    setFile(null)
    onInput({ name: '' } as File)
    fileRef.current!.value = ''
  }

  return (
    <div className={className}>
      {label && (
        <label className="form-label" htmlFor={name}>
          {label}:
        </label>
      )}
      <div className={`form-input p-0 ${error && 'error'}`}>
        <input
          id={name}
          ref={fileRef}
          accept={accept}
          type="file"
          className="hidden"
          onInput={handleFileChange}
        />
        {!file && (
          <div className="p-2">
            <Button text="Browse" onClick={browse} />
          </div>
        )}
        {file && (
          <div className="flex items-center justify-between p-2">
            <div className="flex-1 pr-1">
              {file.name}
              <span className="ml-1 text-gray-600 text-xs">
                ({filesize(file.size)})
              </span>
            </div>
            <Button text="Remove" onClick={remove} />
          </div>
        )}
      </div>
      {error && <div className="form-error">{error}</div>}
    </div>
  )
}
