// packages/presets/templates/default/vue-ts/resources/components/footer.vue
<template>
  <footer>
    <div className="container">
      <p>
        Build with <a href="https://laravel.com/" target="_blank" rel="noreferrer">Laravel</a>, <a
          href="https://vuejs.org/" target="_blank" rel="noreferrer">Vue</a>, <a href="https://inertiajs-revamped.com/"
          target="_blank" rel="noreferrer">Inertia.js-Revamped</a>.
      </p>
    </div>
  </footer>
</template>

// packages/presets/templates/preact/resources/components/footer.jsx
export default function Footer() {
  return (
    <footer>
      <div className="container">
        <p>
          Build with{' '}
          <a href="https://laravel.com/" target="_blank" rel="noreferrer">
            Laravel
          </a>
          ,{' '}
          <a href="https://preactjs.com/" target="_blank" rel="noreferrer">
            Preact
          </a>
          ,{' '}
          <a
            href="https://inertiajs-revamped.com/"
            target="_blank"
            rel="noreferrer"
          >
            Inertia.js-Revamped
          </a>
          .
        </p>
      </div>
    </footer>
  )
}
