// packages/presets/templates/breeze/vue-ts/resources/components/checkbox.vue
<script setup lang="ts">
import { computed } from 'vue'

const emit = defineEmits(['update:checked'])

const props = defineProps<{
  checked: boolean
  value?: any
}>()

const proxyChecked = computed({
  get() {
    return props.checked
  },

  set(val) {
    emit('update:checked', val)
  },
})
</script>

<template>
  <input type="checkbox" :value="value" v-model="proxyChecked"
    class="rounded dark:bg-gray-900 border-gray-300 dark:border-gray-700 text-indigo-600 shadow-sm focus:ring-indigo-500 dark:focus:ring-indigo-600 dark:focus:ring-offset-gray-800" />
</template>

// packages/presets/templates/breeze/react-ts/resources/components/checkbox.tsx
// @ts-nocheck
import type { InputHTMLAttributes } from 'react'

export default function Checkbox({
  className = '',
  ...props
}: InputHTMLAttributes<HTMLInputElement>) {
  return (
    <input
      {...props}
      type="checkbox"
      className={
        'rounded dark:bg-gray-900 border-gray-300 dark:border-gray-700 text-indigo-600 shadow-sm focus:ring-indigo-500 dark:focus:ring-indigo-600 dark:focus:ring-offset-gray-800 ' +
        className
      }
    />
  )
}
