// packages/presets/templates/pingcrm/react/resources/components/pagination.tsx
// @ts-nocheck
import { Link, type PaginationLink } from '@inertiajs-revamped/react'

export interface PaginationProps {
  links: PaginationLink[]
}
export default function Pagination({ links }: PaginationProps) {
  return (
    <div className="mt-6">
      {Array.isArray(links) && links.length > 3 && (
        <div className="flex flex-wrap -mb-1">
          {links.map(({ active, label, url }) => {
            if (url === null) {
              return (
                <div
                  key={label}
                  className="mb-1 mr-1 px-4 py-3 text-gray-400 text-sm leading-4 border rounded"
                >
                  <span dangerouslySetInnerHTML={{ __html: label }}></span>
                </div>
              )
            }

            return (
              <Link
                key={`link-${label}`}
                className={`mb-1 mr-1 px-4 py-3 focus:text-indigo-500 text-sm leading-4 hover:bg-white border focus:border-indigo-500 rounded ${
                  active ? 'bg-white' : ''
                }`}
                href={url}
              >
                <span dangerouslySetInnerHTML={{ __html: label }}></span>
              </Link>
            )
          })}
        </div>
      )}
    </div>
  )
}

// packages/presets/templates/pingcrm/vue/resources/components/pagination.vue
<script setup lang="ts">
import { Link, type PaginationLink } from '@inertiajs-revamped/vue'
import type { PropType } from 'vue'

defineProps({
  links: {
    type: Array as PropType<PaginationLink[]>,
    required: true,
  },
})
</script>

<template>
  <div v-if="links.length > 3">
    <div class="flex flex-wrap -mb-1">
      <template v-for="(link, key) in links">
        <div v-if="link.url === null" :key="key"
          class="mb-1 mr-1 px-4 py-3 text-gray-400 text-sm leading-4 border rounded" v-html="link.label" />
        <Link v-else :key="`link-${key}`"
          class="mb-1 mr-1 px-4 py-3 focus:text-indigo-500 text-sm leading-4 hover:bg-white border focus:border-indigo-500 rounded"
          :class="{ 'bg-white': link.active }" :href="link.url" v-html="link.label" />
      </template>
    </div>
  </div>
</template>
