// packages/presets/templates/vue-ts/resources/views/pages/example.vue
<script setup lang="ts">
import { Head } from '@inertiajs-revamped/vue'
import Counter from '@/views/components/counter.vue'
</script>

<script lang="ts">
import DefaultLayout from '@/views/layouts/default.vue'

export default {
  layout: DefaultLayout,
}
</script>

<template>
  <div>
    <Head title="Example" />

    <h1>Counter</h1>
    <p>This is a simple, hydrated <code>Counter</code> component.</p>
    <Counter />
  </div>
</template>

// packages/presets/templates/preact/resources/views/pages/example.jsx
import { Head, withLayout } from '@inertiajs-revamped/preact'

import Counter from '@/views/components/counter'
import Layout from '@/views/layouts/default'

const Example = () => {
  return (
    <>
      <Head title="Example" />
      <h1>Counter</h1>
      <p>
        This is a simple, hydrated <code>Counter</code> component.
      </p>
      <Counter />
    </>
  )
}

Example.layout = withLayout(Layout)

export default Example
