// packages/presets/templates/vue/resources/views/components/header.vue
<script setup>
import { Link as RouterLink } from '@inertiajs-revamped/vue'
</script>

<template>
  <header>
    <nav class="container">
      <h2>
        <RouterLink href="/">Vue App</RouterLink>
      </h2>
      <ul>
        <li>
          <RouterLink href="/">Home</RouterLink>
        </li>
        <li>
          <RouterLink href="/example">Example</RouterLink>
        </li>
      </ul>
    </nav>
  </header>
</template>

// packages/presets/templates/react/resources/views/components/header.jsx
import { Link } from '@inertiajs-revamped/react'

export default function Header() {
  return (
    <header>
      <nav className="container">
        <h2>
          <Link href="/">React App</Link>
        </h2>
        <ul>
          <li>
            <Link href="/">Home</Link>
          </li>
          <li>
            <Link href="/example">Example</Link>
          </li>
        </ul>
      </nav>
    </header>
  )
}
