// packages/presets/templates/breeze/react/resources/pages/dashboard.tsx
// @ts-nocheck
import AuthenticatedLayout from '@/layouts/authenticated-layout'
import { Head, type PageProps } from '@inertiajs-revamped/react'

export default function Dashboard({ auth }: PageProps) {
  return (
    <AuthenticatedLayout
      user={auth.user}
      header={
        <h2 className="font-semibold text-xl text-gray-800 dark:text-gray-200 leading-tight">
          Dashboard
        </h2>
      }
    >
      <Head title="Dashboard" />

      <div className="py-12">
        <div className="max-w-7xl mx-auto sm:px-6 lg:px-8">
          <div className="bg-white dark:bg-gray-800 overflow-hidden shadow-sm sm:rounded-lg">
            <div className="p-6 text-gray-900 dark:text-gray-100">
              You're logged in!
            </div>
          </div>
        </div>
      </div>
    </AuthenticatedLayout>
  )
}

// packages/presets/templates/breeze/vue/resources/pages/dashboard.vue
<script setup lang="ts">
import AuthenticatedLayout from '@/layouts/authenticated-layout.vue'
import { Head } from '@inertiajs-revamped/vue'
</script>

<template>

  <Head title="Dashboard" />
  <AuthenticatedLayout>
    <template #header>
      <h2 class="font-semibold text-xl text-gray-800 dark:text-gray-200 leading-tight">Dashboard</h2>
    </template>
    <div class="py-12">
      <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
        <div class="bg-white dark:bg-gray-800 overflow-hidden shadow-sm sm:rounded-lg">
          <div class="p-6 text-gray-900 dark:text-gray-100">You're logged in!</div>
        </div>
      </div>
    </div>
  </AuthenticatedLayout>
</template>
