// packages/presets/templates/breeze/react/resources/layouts/guest-layout.tsx
// @ts-nocheck
import ApplicationLogo from '@/components/application-logo'
import { type LayoutProps, Link } from '@inertiajs-revamped/react'

export default function Guest({ children }: LayoutProps) {
  return (
    <div className="min-h-screen flex flex-col sm:justify-center items-center pt-6 sm:pt-0 bg-gray-100 dark:bg-gray-900">
      <div>
        <Link href="/">
          <ApplicationLogo className="w-20 h-20 fill-current text-gray-500" />
        </Link>
      </div>

      <div className="w-full sm:max-w-md mt-6 px-6 py-4 bg-white dark:bg-gray-800 shadow-md overflow-hidden sm:rounded-lg">
        {children}
      </div>
    </div>
  )
}

// packages/presets/templates/breeze/vue/resources/layouts/guest-layout.vue
<script setup lang="ts">
import ApplicationLogo from '@/components/application-logo.vue'
import { Link } from '@inertiajs-revamped/vue'
</script>

<template>
  <div class="min-h-screen flex flex-col sm:justify-center items-center pt-6 sm:pt-0 bg-gray-100 dark:bg-gray-900">
    <div>
      <Link href="/">
      <ApplicationLogo class="w-20 h-20 fill-current text-gray-500" />
      </Link>
    </div>

    <div class="w-full sm:max-w-md mt-6 px-6 py-4 bg-white dark:bg-gray-800 shadow-md overflow-hidden sm:rounded-lg">
      <slot />
    </div>
  </div>
</template>
