// packages/presets/templates/pingcrm/vue-ts/resources/pages/contacts/edit.vue
<script setup lang="ts">
import LoadingButton from '@/components/loading-button.vue'
import SelectInput from '@/components/select-input.vue'
import TextInput from '@/components/text-input.vue'
import TrashedMessage from '@/components/trashed-message.vue'
import Layout from '@/layouts/layout.vue'
import {
  Head,
  Link,
  type PageProps,
  router,
  useForm,
} from '@inertiajs-revamped/vue'
import type { PropType } from 'vue'

defineOptions({ layout: Layout })

const props = defineProps({
  contact: {
    type: Object as PropType<PageProps['contact']>,
    required: true,
  },
  organizations: {
    type: Array as PropType<PageProps['organizations']>,
    required: true,
  },
})

const form = useForm({
  first_name: props.contact.first_name,
  last_name: props.contact.last_name,
  organization_id: props.contact.organization_id,
  email: props.contact.email,
  phone: props.contact.phone,
  address: props.contact.address,
  city: props.contact.city,
  region: props.contact.region,
  country: props.contact.country,
  postal_code: props.contact.postal_code,
})

const update = () => {
  form.put(`/contacts/${props.contact.id}`)
}

const destroy = () => {
  if (confirm('Are you sure you want to delete this contact?')) {
    router.delete(`/contacts/${props.contact.id}`)
  }
}

const restore = () => {
  if (confirm('Are you sure you want to restore this contact?')) {
    router.put(`/contacts/${props.contact.id}/restore`)
  }
}
</script>

<template>

  <Head :title="`${form.first_name} ${form.last_name}`" />
  <h1 class="mb-8 text-3xl font-bold">
    <Link class="text-indigo-400 hover:text-indigo-600" href="/contacts">Contacts</Link>
    <span class="font-medium"> /</span>
    {{ form.first_name }} {{ form.last_name }}
  </h1>
  <TrashedMessage v-if="contact.deleted_at" class="mb-6" @restore="restore"> This contact has been deleted.
  </TrashedMessage>
  <div class="max-w-3xl bg-white rounded-md shadow overflow-hidden">
    <form @submit.prevent="update">
      <div class="flex flex-wrap -mb-8 -mr-6 p-8">
        <TextInput v-model="form.first_name" :error="form.errors.first_name" class="pb-8 pr-6 w-full lg:w-1/2"
          label="First name" />
        <TextInput v-model="form.last_name" :error="form.errors.last_name" class="pb-8 pr-6 w-full lg:w-1/2"
          label="Last name" />
        <SelectInput v-model="form.organization_id" :error="form.errors.organization_id"
          class="pb-8 pr-6 w-full lg:w-1/2" label="Organization">
          <option :value="null" />
          <option v-for="organization in organizations" :key="organization.id" :value="organization.id">{{
            organization.name }}</option>
        </SelectInput>
        <TextInput v-model="form.email" :error="form.errors.email" class="pb-8 pr-6 w-full lg:w-1/2" label="Email" />
        <TextInput v-model="form.phone" :error="form.errors.phone" class="pb-8 pr-6 w-full lg:w-1/2" label="Phone" />
        <TextInput v-model="form.address" :error="form.errors.address" class="pb-8 pr-6 w-full lg:w-1/2"
          label="Address" />
        <TextInput v-model="form.city" :error="form.errors.city" class="pb-8 pr-6 w-full lg:w-1/2" label="City" />
        <TextInput v-model="form.region" :error="form.errors.region" class="pb-8 pr-6 w-full lg:w-1/2"
          label="Province/State" />
        <SelectInput v-model="form.country" :error="form.errors.country" class="pb-8 pr-6 w-full lg:w-1/2"
          label="Country">
          <option :value="null" />
          <option value="CA">Canada</option>
          <option value="US">United States</option>
        </SelectInput>
        <TextInput v-model="form.postal_code" :error="form.errors.postal_code" class="pb-8 pr-6 w-full lg:w-1/2"
          label="Postal code" />
      </div>
      <div class="flex items-center px-8 py-4 bg-gray-50 border-t border-gray-100">
        <button v-if="!contact.deleted_at" class="text-red-600 hover:underline" tabindex="-1" type="button"
          @click="destroy">Delete Contact</button>
        <LoadingButton :loading="form.processing" class="btn-indigo ml-auto" type="submit">Update Contact
        </LoadingButton>
      </div>
    </form>
  </div>
</template>

// packages/presets/templates/pingcrm/react/resources/pages/contacts/edit.tsx
// @ts-nocheck
import LoadingButton from '@/components/loading-button'
import SelectInput from '@/components/select-input'
import TextInput from '@/components/text-input'
import TrashedMessage from '@/components/trashed-message'
import Layout from '@/layouts/layout'
import {
  Head,
  Link,
  router,
  useForm,
  usePage,
  withLayout,
} from '@inertiajs-revamped/react'
import type { FormEvent } from 'react'

export function Edit() {
  const { contact, organizations } = usePage().props

  const { data, setData, errors, put, processing } = useForm({
    first_name: contact.first_name || '',
    last_name: contact.last_name || '',
    organization_id: contact.organization_id || '',
    email: contact.email || '',
    phone: contact.phone || '',
    address: contact.address || '',
    city: contact.city || '',
    region: contact.region || '',
    country: contact.country || '',
    postal_code: contact.postal_code || '',
  })

  const handleSubmit = (e: FormEvent<HTMLFormElement>) => {
    e.preventDefault()
    put(`/contacts/${contact.id}`)
  }

  const handleDestroy = () => {
    if (confirm('Are you sure you want to delete this contact?')) {
      router.delete(`/contacts/${contact.id}`)
    }
  }

  const handleRestore = () => {
    if (confirm('Are you sure you want to restore this contact?')) {
      router.put(`/contacts/${contact.id}/restore`)
    }
  }

  return (
    <>
      <Head title={`${data.first_name} ${data.last_name}`} />
      <h1 className="mb-8 text-3xl font-bold">
        <Link
          className="text-indigo-400 hover:text-indigo-600"
          href="/contacts"
        >
          Contacts
        </Link>
        <span className="text-indigo-400 font-medium"> / </span>
        {data.first_name} {data.last_name}
      </h1>
      {contact.deleted_at && (
        <TrashedMessage className="mb-6" onRestore={handleRestore}>
          This contact has been deleted.
        </TrashedMessage>
      )}
      <div className="max-w-3xl bg-white rounded-md shadow overflow-hidden">
        <form onSubmit={handleSubmit}>
          <div className="flex flex-wrap -mb-8 -mr-6 p-8">
            <TextInput
              className="pb-8 pr-6 w-full lg:w-1/2"
              label="First name"
              name="first_name"
              type="text"
              error={errors.first_name}
              value={data.first_name}
              onChange={(e) => setData('first_name', e.target.value)}
            />
            <TextInput
              className="pb-8 pr-6 w-full lg:w-1/2"
              label="Last name"
              name="last_name"
              type="text"
              error={errors.last_name}
              value={data.last_name}
              onChange={(e) => setData('last_name', e.target.value)}
            />
            <SelectInput
              className="pb-8 pr-6 w-full lg:w-1/2"
              label="Organization"
              name="organization_id"
              error={errors.organization_id}
              onChange={(e) => setData('organization_id', e.target.value)}
              defaultValue={data.organization_id}
            >
              <option value="null" />
              {Array.isArray(organizations) &&
                organizations.map(({ id, name }) => (
                  <option key={id} value={id}>
                    {name}
                  </option>
                ))}
            </SelectInput>
            <TextInput
              className="pb-8 pr-6 w-full lg:w-1/2"
              label="Email"
              name="email"
              type="email"
              error={errors.email}
              value={data.email}
              onChange={(e) => setData('email', e.target.value)}
            />
            <TextInput
              className="pb-8 pr-6 w-full lg:w-1/2"
              label="Phone"
              name="phone"
              type="text"
              error={errors.phone}
              value={data.phone}
              onChange={(e) => setData('phone', e.target.value)}
            />
            <TextInput
              className="pb-8 pr-6 w-full lg:w-1/2"
              label="Address"
              name="address"
              type="text"
              error={errors.address}
              value={data.address}
              onChange={(e) => setData('address', e.target.value)}
            />
            <TextInput
              className="pb-8 pr-6 w-full lg:w-1/2"
              label="City"
              name="city"
              type="text"
              error={errors.city}
              value={data.city}
              onChange={(e) => setData('city', e.target.value)}
            />
            <TextInput
              className="pb-8 pr-6 w-full lg:w-1/2"
              label="Province/State"
              name="region"
              type="text"
              error={errors.region}
              value={data.region}
              onChange={(e) => setData('region', e.target.value)}
            />
            <SelectInput
              className="pb-8 pr-6 w-full lg:w-1/2"
              label="Country"
              name="country"
              error={errors.country}
              onChange={(e) => setData('country', e.target.value)}
              defaultValue={data.country}
            >
              <option value="null" />
              <option value="CA">Canada</option>
              <option value="US">United States</option>
            </SelectInput>
            <TextInput
              className="pb-8 pr-6 w-full lg:w-1/2"
              label="Postal code"
              name="postal_code"
              type="text"
              error={errors.postal_code}
              onChange={(e) => setData('postal_code', e.target.value)}
              defaultValue={data.postal_code}
            />
          </div>
          <div className="flex items-center px-8 py-4 bg-gray-50 border-t border-gray-100">
            {!contact.deleted_at && (
              <button
                className="text-red-600 hover:underline"
                tabIndex={-1}
                type="button"
                onClick={handleDestroy}
              >
                Delete Contact
              </button>
            )}
            <LoadingButton
              loading={processing}
              className="btn-indigo ml-auto"
              type="submit"
            >
              Update Contact
            </LoadingButton>
          </div>
        </form>
      </div>
    </>
  )
}

Edit.layout = withLayout(Layout)

export default Edit
