// packages/presets/templates/breeze/react/resources/pages/auth/verify-email.tsx
// @ts-nocheck
import PrimaryButton from '@/components/primary-button'
import GuestLayout from '@/layouts/guest-layout'
import { Head, Link, useForm } from '@inertiajs-revamped/react'
import type { FormEventHandler } from 'react'

export default function VerifyEmail({ status }: { status?: string }) {
  const { post, processing } = useForm({})

  const submit: FormEventHandler = (e) => {
    e.preventDefault()

    post('/email/verification-notification')
  }

  return (
    <GuestLayout>
      <Head title="Email Verification" />

      <div className="mb-4 text-sm text-gray-600 dark:text-gray-400">
        Thanks for signing up! Before getting started, could you verify your
        email address by clicking on the link we just emailed to you? If you
        didn't receive the email, we will gladly send you another.
      </div>

      {status === 'verification-link-sent' && (
        <div className="mb-4 font-medium text-sm text-green-600 dark:text-green-400">
          A new verification link has been sent to the email address you
          provided during registration.
        </div>
      )}

      <form onSubmit={submit}>
        <div className="mt-4 flex items-center justify-between">
          <PrimaryButton disabled={processing}>
            Resend Verification Email
          </PrimaryButton>

          <Link
            href="/logout"
            method="post"
            as="button"
            className="underline text-sm text-gray-600 dark:text-gray-400 hover:text-gray-900 dark:hover:text-gray-100 rounded-md focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 dark:focus:ring-offset-gray-800"
          >
            Log Out
          </Link>
        </div>
      </form>
    </GuestLayout>
  )
}

// packages/presets/templates/breeze/vue-ts/resources/pages/auth/verify-email.vue
<script setup lang="ts">
import PrimaryButton from '@/components/primary-button.vue'
import GuestLayout from '@/layouts/guest-layout.vue'
import { Head, Link, useForm } from '@inertiajs-revamped/vue'
import { computed } from 'vue'

const props = defineProps<{
  status?: string
}>()

const form = useForm({})

const submit = () => {
  form.post('email/verification-notification')
}

const verificationLinkSent = computed(
  () => props.status === 'verification-link-sent'
)
</script>

<template>
  <GuestLayout>

    <Head title="Email Verification" />

    <div class="mb-4 text-sm text-gray-600 dark:text-gray-400">
      Thanks for signing up! Before getting started, could you verify your email address by clicking on the link
      we just emailed to you? If you didn't receive the email, we will gladly send you another.
    </div>

    <div class="mb-4 font-medium text-sm text-green-600 dark:text-green-400" v-if="verificationLinkSent">
      A new verification link has been sent to the email address you provided during registration.
    </div>

    <form @submit.prevent="submit">
      <div class="mt-4 flex items-center justify-between">
        <PrimaryButton :class="{ 'opacity-25': form.processing }" :disabled="form.processing">
          Resend Verification Email
        </PrimaryButton>

        <Link href="/logout" method="post" as="button"
          class="underline text-sm text-gray-600 dark:text-gray-400 hover:text-gray-900 dark:hover:text-gray-100 rounded-md focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 dark:focus:ring-offset-gray-800">
        Log Out</Link>
      </div>
    </form>
  </GuestLayout>
</template>
