// packages/presets/templates/pingcrm/vue-ts/resources/pages/users/edit.vue
<script setup lang="ts">
import FileInput from '@/components/file-input.vue'
import LoadingButton from '@/components/loading-button.vue'
import SelectInput from '@/components/select-input.vue'
import TextInput from '@/components/text-input.vue'
import TrashedMessage from '@/components/trashed-message.vue'
import Layout from '@/layouts/layout.vue'
import { Head, Link, router, useForm } from '@inertiajs-revamped/vue'
import type { PropType } from 'vue'

defineOptions({ layout: Layout })

const props = defineProps({
  user: {
    type: Object as PropType<App.Models.User & { photo: string | null }>,
    required: true,
  },
})

const form = useForm({
  _method: 'put',
  first_name: props.user.first_name,
  last_name: props.user.last_name,
  email: props.user.email,
  password: '',
  owner: props.user.owner,
  photo: null,
})

const update = () => {
  form.post(`/users/${props.user.id}`, {
    onSuccess: () => form.reset('password', 'photo'),
  })
}

const destroy = () => {
  if (confirm('Are you sure you want to delete this user?')) {
    router.delete(`/users/${props.user.id}`)
  }
}

const restore = () => {
  if (confirm('Are you sure you want to restore this user?')) {
    router.put(`/users/${props.user.id}/restore`)
  }
}
</script>

<template>

  <Head :title="`${form.first_name} ${form.last_name}`" />
  <div class="flex justify-start mb-8 max-w-3xl">
    <h1 class="text-3xl font-bold">
      <Link class="text-indigo-400 hover:text-indigo-600" href="/users">Users</Link>
      <span class="font-medium"> /</span>
      {{ form.first_name }} {{ form.last_name }}
    </h1>
    <img v-if="user.photo" class="block ml-4 w-8 h-8 rounded-full" :src="user.photo" />
  </div>
  <TrashedMessage v-if="user.deleted_at" class="mb-6" @restore="restore"> This user has been deleted.
  </TrashedMessage>
  <div class="max-w-3xl bg-white rounded-md shadow overflow-hidden">
    <form @submit.prevent="update">
      <div class="flex flex-wrap -mb-8 -mr-6 p-8">
        <TextInput v-model="form.first_name" :error="form.errors.first_name" class="pb-8 pr-6 w-full lg:w-1/2"
          label="First name" />
        <TextInput v-model="form.last_name" :error="form.errors.last_name" class="pb-8 pr-6 w-full lg:w-1/2"
          label="Last name" />
        <TextInput v-model="form.email" :error="form.errors.email" class="pb-8 pr-6 w-full lg:w-1/2" label="Email" />
        <TextInput v-model="form.password" :error="form.errors.password" class="pb-8 pr-6 w-full lg:w-1/2"
          type="password" autocomplete="new-password" label="Password" />
        <SelectInput v-model="form.owner" :error="form.errors.owner" class="pb-8 pr-6 w-full lg:w-1/2" label="Owner">
          <option :value="true">Yes</option>
          <option :value="false">No</option>
        </SelectInput>
        <FileInput v-model="form.photo" :error="form.errors.photo" class="pb-8 pr-6 w-full lg:w-1/2" type="file"
          accept="image/*" label="Photo" />
      </div>
      <div class="flex items-center px-8 py-4 bg-gray-50 border-t border-gray-100">
        <button v-if="!user.deleted_at" class="text-red-600 hover:underline" tabindex="-1" type="button"
          @click="destroy">Delete User</button>
        <LoadingButton :loading="form.processing" class="btn-indigo ml-auto" type="submit">Update
          User</LoadingButton>
      </div>
    </form>
  </div>
</template>

// packages/presets/templates/pingcrm/react/resources/pages/users/edit.tsx
// @ts-nocheck
import FileInput from '@/components/file-input'
import LoadingButton from '@/components/loading-button'
import SelectInput from '@/components/select-input'
import TextInput from '@/components/text-input'
import TrashedMessage from '@/components/trashed-message'
import Layout from '@/layouts/layout'
import { withLayout } from '@inertiajs-revamped/react'
import { Head, Link, router, useForm, usePage } from '@inertiajs-revamped/react'
import type { FormEvent } from 'react'

export function Edit() {
  const { user } = usePage().props

  const { data, setData, errors, post, processing } = useForm({
    _method: 'PUT',
    first_name: user.first_name || '',
    last_name: user.last_name || '',
    email: user.email || '',
    password: user.password || '',
    owner: user.owner ? '1' : '0' || '0',
    photo: '',
  })

  const handleSubmit = (e: FormEvent<HTMLFormElement>) => {
    e.preventDefault()
    post(`/users/${user.id}`)
  }

  const handleDestroy = () => {
    if (confirm('Are you sure you want to delete this user?')) {
      router.delete(`/users/${user.id}`)
    }
  }

  const handleRestore = () => {
    if (confirm('Are you sure you want to restore this user?')) {
      router.put(`/users/${user.id}/restore`)
    }
  }

  return (
    <>
      <Head title={`${data.first_name} ${data.last_name}`} />
      <div className="flex justify-start mb-8 max-w-3xl">
        <h1 className="text-3xl font-bold">
          <Link className="text-indigo-400 hover:text-indigo-600" href="/users">
            Users
          </Link>
          <span className="text-indigo-400 font-medium"> / </span>
          {data.first_name} {data.last_name}
        </h1>
        {user.photo && (
          <img
            className="block ml-4 w-8 h-8 rounded-full"
            src={user.photo}
            alt={data.first_name}
          />
        )}
      </div>
      {user.deleted_at && (
        <TrashedMessage onRestore={handleRestore}>
          This user has been deleted.
        </TrashedMessage>
      )}
      <div className="max-w-3xl bg-white rounded-md shadow overflow-hidden">
        <form onSubmit={handleSubmit}>
          <div className="flex flex-wrap -mb-8 -mr-6 p-8">
            <TextInput
              className="pb-8 pr-6 w-full lg:w-1/2"
              label="First name"
              name="first_name"
              type="text"
              error={errors.first_name}
              value={data.first_name}
              onChange={(e) => setData('first_name', e.target.value)}
            />
            <TextInput
              className="pb-8 pr-6 w-full lg:w-1/2"
              label="Last name"
              name="last_name"
              type="text"
              error={errors.last_name}
              value={data.last_name}
              onChange={(e) => setData('last_name', e.target.value)}
            />
            <TextInput
              className="pb-8 pr-6 w-full lg:w-1/2"
              label="Email"
              name="email"
              type="email"
              error={errors.email}
              value={data.email}
              onChange={(e) => setData('email', e.target.value)}
            />
            <TextInput
              className="pb-8 pr-6 w-full lg:w-1/2"
              label="Password"
              name="password"
              type="password"
              error={errors.password}
              value={data.password}
              onChange={(e) => setData('password', e.target.value)}
            />
            <SelectInput
              className="pb-8 pr-6 w-full lg:w-1/2"
              label="Owner"
              name="owner"
              error={errors.owner}
              onChange={(e) => setData('owner', e.target.value)}
              defaultValue={data.owner}
            >
              <option value="1">Yes</option>
              <option value="0">No</option>
            </SelectInput>
            <FileInput
              className="pb-8 pr-6 w-full lg:w-1/2"
              label="Photo"
              name="photo"
              error={errors.photo}
              value={data.photo}
              accept="image/*"
              onInput={(photo) => setData('photo', photo.name)}
            />
          </div>
          <div className="flex items-center px-8 py-4 bg-gray-50 border-t border-gray-100">
            {!user.deleted_at && (
              <button
                className="text-red-600 hover:underline"
                tabIndex={-1}
                type="button"
                onClick={handleDestroy}
              >
                Delete User
              </button>
            )}
            <LoadingButton
              loading={processing}
              className="btn-indigo ml-auto"
              type="submit"
            >
              Update User
            </LoadingButton>
          </div>
        </form>
      </div>
    </>
  )
}

Edit.layout = withLayout(Layout)

export default Edit
