// packages/presets/templates/default/vue/resources/pages/example.vue
<script setup>
import Counter from '@/components/counter.vue'
import DefaultLayout from '@/layouts/default.vue'
import { Head } from '@inertiajs-revamped/vue'

defineOptions({ layout: DefaultLayout })
</script>

<template>

  <Head title="Example" />
  <h1>Counter</h1>
  <p>This is a simple, hydrated <code>Counter</code> component.</p>
  <Counter />

</template>

// packages/presets/templates/react-ts/resources/pages/example.tsx
// @ts-nocheck
import { Head, withLayout } from '@inertiajs-revamped/react'

import Counter from '@/components/counter'
import Layout from '@/layouts/default'

const Example = () => {
  return (
    <>
      <Head title="Example" />
      <h1>Counter</h1>
      <p>
        This is a simple, hydrated <code>Counter</code> component.
      </p>
      <Counter />
    </>
  )
}

Example.layout = withLayout(Layout)

export default Example
