// packages/presets/templates/pingcrm/vue/resources/pages/organizations/edit.vue
<script setup lang="ts">
import Icon from '@/components/icon.vue'
import LoadingButton from '@/components/loading-button.vue'
import SelectInput from '@/components/select-input.vue'
import TextInput from '@/components/text-input.vue'
import TrashedMessage from '@/components/trashed-message.vue'
import Layout from '@/layouts/layout.vue'
import {
  Head,
  Link,
  type PageProps,
  router,
  useForm,
} from '@inertiajs-revamped/vue'
import type { PropType } from 'vue'

defineOptions({ layout: Layout })

const props = defineProps({
  organization: {
    type: Object as PropType<PageProps['organization']>,
    required: true,
  },
})

const form = useForm({
  name: props.organization.name,
  email: props.organization.email,
  phone: props.organization.phone,
  address: props.organization.address,
  city: props.organization.city,
  region: props.organization.region,
  country: props.organization.country,
  postal_code: props.organization.postal_code,
})

const update = () => {
  form.put(`/organizations/${props.organization.id}`)
}

const destroy = () => {
  if (confirm('Are you sure you want to delete this organization?')) {
    router.delete(`/organizations/${props.organization.id}`)
  }
}

const restore = () => {
  if (confirm('Are you sure you want to restore this organization?')) {
    router.put(`/organizations/${props.organization.id}/restore`)
  }
}
</script>

<template>

  <Head :title="form.name" />
  <h1 class="mb-8 text-3xl font-bold">
    <Link class="text-indigo-400 hover:text-indigo-600" href="/organizations">Organizations</Link>
    <span class="font-medium"> /</span>
    {{ form.name }}
  </h1>
  <TrashedMessage v-if="organization.deleted_at" class="mb-6" @restore="restore"> This organization has been deleted.
  </TrashedMessage>
  <div class="max-w-3xl bg-white rounded-md shadow overflow-hidden">
    <form @submit.prevent="update">
      <div class="flex flex-wrap -mb-8 -mr-6 p-8">
        <TextInput v-model="form.name" :error="form.errors.name" class="pb-8 pr-6 w-full lg:w-1/2" label="Name" />
        <TextInput v-model="form.email" :error="form.errors.email" class="pb-8 pr-6 w-full lg:w-1/2" label="Email" />
        <TextInput v-model="form.phone" :error="form.errors.phone" class="pb-8 pr-6 w-full lg:w-1/2" label="Phone" />
        <TextInput v-model="form.address" :error="form.errors.address" class="pb-8 pr-6 w-full lg:w-1/2"
          label="Address" />
        <TextInput v-model="form.city" :error="form.errors.city" class="pb-8 pr-6 w-full lg:w-1/2" label="City" />
        <TextInput v-model="form.region" :error="form.errors.region" class="pb-8 pr-6 w-full lg:w-1/2"
          label="Province/State" />
        <SelectInput v-model="form.country" :error="form.errors.country" class="pb-8 pr-6 w-full lg:w-1/2"
          label="Country">
          <option :value="null" />
          <option value="CA">Canada</option>
          <option value="US">United States</option>
        </SelectInput>
        <TextInput v-model="form.postal_code" :error="form.errors.postal_code" class="pb-8 pr-6 w-full lg:w-1/2"
          label="Postal code" />
      </div>
      <div class="flex items-center px-8 py-4 bg-gray-50 border-t border-gray-100">
        <button v-if="!organization.deleted_at" class="text-red-600 hover:underline" tabindex="-1" type="button"
          @click="destroy">Delete Organization</button>
        <LoadingButton :loading="form.processing" class="btn-indigo ml-auto" type="submit">Update Organization
        </LoadingButton>
      </div>
    </form>
  </div>
  <h2 class="mt-12 text-2xl font-bold">Contacts</h2>
  <div class="mt-6 bg-white rounded shadow overflow-x-auto">
    <table class="w-full whitespace-nowrap">
      <tr class="text-left font-bold">
        <th class="pb-4 pt-6 px-6">Name</th>
        <th class="pb-4 pt-6 px-6">City</th>
        <th class="pb-4 pt-6 px-6" colspan="2">Phone</th>
      </tr>
      <tr v-for="contact in organization.contacts" :key="contact.id" class="hover:bg-gray-100 focus-within:bg-gray-100">
        <td class="border-t">
          <Link class="flex items-center px-6 py-4 focus:text-indigo-500" :href="`/contacts/${contact.id}/edit`">
          {{ contact.name }}
          <Icon v-if="contact.deleted_at" name="trash" class="shrink-0 ml-2 w-3 h-3 fill-gray-400" />
          </Link>
        </td>
        <td class="border-t">
          <Link class="flex items-center px-6 py-4" :href="`/contacts/${contact.id}/edit`" tabindex="-1">
          {{ contact.city }}
          </Link>
        </td>
        <td class="border-t">
          <Link class="flex items-center px-6 py-4" :href="`/contacts/${contact.id}/edit`" tabindex="-1">
          {{ contact.phone }}
          </Link>
        </td>
        <td class="w-px border-t">
          <Link class="flex items-center px-4" :href="`/contacts/${contact.id}/edit`" tabindex="-1">
          <Icon name="cheveron-right" class="block w-6 h-6 fill-gray-400" />
          </Link>
        </td>
      </tr>
      <tr v-if="Array.isArray(organization.contacts) && organization.contacts.length === 0">
        <td class="px-6 py-4 border-t" colspan="4">No contacts found.</td>
      </tr>
    </table>
  </div>
</template>

// packages/presets/templates/pingcrm/react/resources/pages/organizations/edit.tsx
// @ts-nocheck
import Icon from '@/components/icon'
import LoadingButton from '@/components/loading-button'
import SelectInput from '@/components/select-input'
import TextInput from '@/components/text-input'
import TrashedMessage from '@/components/trashed-message'
import Layout from '@/layouts/layout'
import {
  Head,
  Link,
  router,
  useForm,
  usePage,
  withLayout,
} from '@inertiajs-revamped/react'
import type { FormEvent } from 'react'

export function Edit() {
  const { organization } = usePage().props

  const { data, setData, errors, put, processing } = useForm({
    name: organization.name || '',
    email: organization.email || '',
    phone: organization.phone || '',
    address: organization.address || '',
    city: organization.city || '',
    region: organization.region || '',
    country: organization.country || '',
    postal_code: organization.postal_code || '',
  })

  const handleSubmit = (e: FormEvent<HTMLFormElement>) => {
    e.preventDefault()
    put(`/organizations/${organization.id}`)
  }

  const handleDestroy = () => {
    if (confirm('Are you sure you want to delete this organization?')) {
      router.delete(`/organizations/${organization.id}`)
    }
  }

  const handleRestore = () => {
    if (confirm('Are you sure you want to restore this organization?')) {
      router.put(`/organizations/${organization.id}/restore`)
    }
  }

  return (
    <>
      <Head title={`${data.name}`} />
      <h1 className="mb-8 text-3xl font-bold">
        <Link
          className="text-indigo-400 hover:text-indigo-600"
          href="/organizations"
        >
          Organizations
        </Link>
        <span className="text-indigo-400 font-medium"> / </span>
        {data.name}
      </h1>
      {organization.deleted_at && (
        <TrashedMessage className="mb-6" onRestore={handleRestore}>
          This organization has been deleted.
        </TrashedMessage>
      )}
      <div className="max-w-3xl bg-white rounded-md shadow overflow-hidden">
        <form onSubmit={handleSubmit}>
          <div className="flex flex-wrap -mb-8 -mr-6 p-8">
            <TextInput
              className="pb-8 pr-6 w-full lg:w-1/2"
              label="Name"
              name="name"
              type="text"
              error={errors.name}
              value={data.name}
              onChange={(e) => setData('name', e.target.value)}
            />
            <TextInput
              className="pb-8 pr-6 w-full lg:w-1/2"
              label="Email"
              name="email"
              type="email"
              error={errors.email}
              value={data.email}
              onChange={(e) => setData('email', e.target.value)}
            />
            <TextInput
              className="pb-8 pr-6 w-full lg:w-1/2"
              label="Phone"
              name="phone"
              type="text"
              error={errors.phone}
              value={data.phone}
              onChange={(e) => setData('phone', e.target.value)}
            />
            <TextInput
              className="pb-8 pr-6 w-full lg:w-1/2"
              label="Address"
              name="address"
              type="text"
              error={errors.address}
              value={data.address}
              onChange={(e) => setData('address', e.target.value)}
            />
            <TextInput
              className="pb-8 pr-6 w-full lg:w-1/2"
              label="City"
              name="city"
              type="text"
              error={errors.city}
              value={data.city}
              onChange={(e) => setData('city', e.target.value)}
            />
            <TextInput
              className="pb-8 pr-6 w-full lg:w-1/2"
              label="Province/State"
              name="region"
              type="text"
              error={errors.region}
              value={data.region}
              onChange={(e) => setData('region', e.target.value)}
            />
            <SelectInput
              className="pb-8 pr-6 w-full lg:w-1/2"
              label="Country"
              name="country"
              error={errors.country}
              value={data.country}
              onChange={(e) => setData('country', e.target.value)}
            >
              <option value="" />
              <option value="CA">Canada</option>
              <option value="US">United States</option>
            </SelectInput>
            <TextInput
              className="pb-8 pr-6 w-full lg:w-1/2"
              label="Postal code"
              name="postal_code"
              type="text"
              error={errors.postal_code}
              value={data.postal_code}
              onChange={(e) => setData('postal_code', e.target.value)}
            />
          </div>
          <div className="flex items-center px-8 py-4 bg-gray-50 border-t border-gray-100">
            {!organization.deleted_at && (
              <button
                className="text-red-600 hover:underline"
                tabIndex={-1}
                type="button"
                onClick={handleDestroy}
              >
                Delete Organization
              </button>
            )}
            <LoadingButton
              loading={processing}
              className="btn-indigo ml-auto"
              type="submit"
            >
              Update Organization
            </LoadingButton>
          </div>
        </form>
      </div>
      <h2 className="mt-12 text-2xl font-bold">Contacts</h2>
      <div className="mt-6 bg-white rounded shadow overflow-x-auto">
        <table className="w-full whitespace-nowrap">
          <thead>
            <tr className="text-left font-bold">
              <th className="pb-4 pt-6 px-6">Name</th>
              <th className="pb-4 pt-6 px-6">City</th>
              <th className="pb-4 pt-6 px-6" colSpan={2}>
                Phone
              </th>
            </tr>
          </thead>
          <tbody>
            {Array.isArray(organization.contacts) &&
              organization.contacts.map(
                ({ id, name, phone, city, deleted_at }) => (
                  <tr
                    key={id}
                    className="hover:bg-gray-100 focus-within:bg-gray-100"
                  >
                    <td className="border-t">
                      <Link
                        className="flex items-center px-6 py-4 focus:text-indigo-500"
                        href={`/contacts/${id}/edit`}
                      >
                        {name}
                        {deleted_at && (
                          <Icon
                            name="trash"
                            className="flex-shrink-0 ml-2 w-3 h-3 fill-gray-400"
                          />
                        )}
                      </Link>
                    </td>
                    <td className="border-t">
                      <Link
                        className="flex items-center px-6 py-4"
                        href={`/contacts/${id}/edit`}
                        tabIndex={-1}
                      >
                        {city}
                      </Link>
                    </td>
                    <td className="border-t">
                      <Link
                        className="flex items-center px-6 py-4"
                        href={`/contacts/${id}/edit`}
                        tabIndex={-1}
                      >
                        {phone}
                      </Link>
                    </td>
                    <td className="w-px border-t">
                      <Link
                        className="flex items-center px-4"
                        href={`/contacts/${id}/edit`}
                        tabIndex={-1}
                      >
                        <Icon
                          name="cheveron-right"
                          className="block w-6 h-6 fill-gray-400"
                        />
                      </Link>
                    </td>
                  </tr>
                )
              )}
            {Array.isArray(organization.contacts) &&
              organization.contacts.length === 0 && (
                <tr>
                  <td className="px-6 py-4 border-t" colSpan={4}>
                    No contacts found.
                  </td>
                </tr>
              )}
          </tbody>
        </table>
      </div>
    </>
  )
}

Edit.layout = withLayout(Layout)

export default Edit
