// packages/presets/templates/pingcrm/vue-ts/resources/pages/organizations/index.vue
<script setup lang="ts">
import Icon from '@/components/icon.vue'
import Pagination from '@/components/pagination.vue'
import SearchFilter from '@/components/search-filter.vue'
import Layout from '@/layouts/layout.vue'
import { pickBy, throttle } from '@/utils'
import { type Filters, Head, Link, type ModelPagination, router } from '@inertiajs-revamped/vue'
import { type PropType, ref, watch } from 'vue'

defineOptions({ layout: Layout })

const props = defineProps({
  filters: {
    type: Object as PropType<Filters>,
    required: true,
  },
  organizations: {
    type: Object as PropType<ModelPagination<App.Models.Organization>>,
    required: true,
  },
})

const form = ref({
  search: props.filters.search,
  trashed: props.filters.trashed,
})

watch(
  form,
  throttle(() => {
    router.get('/organizations', pickBy(form.value), { preserveState: true })
  }, 150),
  { deep: true },
)

const reset = () => {
  form.value = {
    search: null,
    trashed: null,
  }
}
</script>

<template>

  <Head title="Organizations" />
  <h1 class="mb-8 text-3xl font-bold">Organizations</h1>
  <div class="flex items-center justify-between mb-6">
    <SearchFilter v-model="form.search" class="mr-4 w-full max-w-md" @reset="reset">
      <label class="block text-gray-700">Trashed:</label>
      <select v-model="form.trashed"
        class="form-select mt-1 w-full focus:outline-none focus:ring-1 focus:ring-indigo-400">
        <option :value="null" />
        <option value="with">With Trashed</option>
        <option value="only">Only Trashed</option>
      </select>
    </SearchFilter>
    <Link class="btn-indigo" href="/organizations/create">
    <span>Create</span>
    <span class="hidden md:inline">&nbsp;Organization</span>
    </Link>
  </div>
  <div class="bg-white rounded-md shadow overflow-x-auto">
    <table class="w-full whitespace-nowrap">
      <thead>
        <tr class="text-left font-bold">
          <th class="pb-4 pt-6 px-6">Name</th>
          <th class="pb-4 pt-6 px-6">City</th>
          <th class="pb-4 pt-6 px-6" colspan="2">Phone</th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="organization in organizations.data" :key="organization.id"
          class="hover:bg-gray-100 focus-within:bg-gray-100">
          <td class="border-t">
            <Link class="flex items-center px-6 py-4 focus:text-indigo-500"
              :href="`/organizations/${organization.id}/edit`">
            {{ organization.name }}
            <Icon v-if="organization.deleted_at" name="trash" class="shrink-0 ml-2 w-3 h-3 fill-gray-400" />
            </Link>
          </td>
          <td class="border-t">
            <Link class="flex items-center px-6 py-4" :href="`/organizations/${organization.id}/edit`" tabindex="-1">
            {{ organization.city }}
            </Link>
          </td>
          <td class="border-t">
            <Link class="flex items-center px-6 py-4" :href="`/organizations/${organization.id}/edit`" tabindex="-1">
            {{ organization.phone }}
            </Link>
          </td>
          <td class="w-px border-t">
            <Link class="flex items-center px-4" :href="`/organizations/${organization.id}/edit`" tabindex="-1">
            <Icon name="cheveron-right" class="block w-6 h-6 fill-gray-400" />
            </Link>
          </td>
        </tr>
        <tr v-if="organizations.data.length === 0">
          <td class="px-6 py-4 border-t" colspan="4">No organizations found.</td>
        </tr>
      </tbody>
    </table>
  </div>
  <Pagination class="mt-6" :links="organizations.links" />
</template>

// packages/presets/templates/pingcrm/react/resources/pages/organizations/index.tsx
// @ts-nocheck
import Icon from '@/components/icon'
import Pagination from '@/components/pagination'
import SearchFilter from '@/components/search-filter'
import Layout from '@/layouts/layout'
import { Head, Link, usePage, withLayout } from '@inertiajs-revamped/react'

const Index = () => {
  const {
    organizations: { data, links },
  } = usePage().props

  return (
    <>
      <Head title="Organizations" />
      <h1 className="mb-8 text-3xl font-bold">Organizations</h1>
      <div className="flex items-center justify-between mb-6">
        <SearchFilter />
        <Link className="btn-indigo" href="/organizations/create">
          <span>Create</span>
          <span className="hidden md:inline">&nbsp;Organization</span>
        </Link>
      </div>
      <div className="bg-white rounded-md shadow overflow-x-auto">
        <table className="w-full whitespace-nowrap">
          <thead>
            <tr className="text-left font-bold">
              <th className="pb-4 pt-6 px-6">Name</th>
              <th className="pb-4 pt-6 px-6">City</th>
              <th className="pb-4 pt-6 px-6" colSpan={2}>
                Phone
              </th>
            </tr>
          </thead>
          <tbody>
            {data.map(({ id, name, phone, city, deleted_at }) => (
              <tr
                key={id}
                className="hover:bg-gray-100 focus-within:bg-gray-100"
              >
                <td className="border-t">
                  <Link
                    className="flex items-center px-6 py-4 focus:text-indigo-500"
                    href={`/organizations/${id}/edit`}
                  >
                    {name}
                    {deleted_at && (
                      <Icon
                        name="trash"
                        className="flex-shrink-0 ml-2 w-3 h-3 fill-gray-400"
                      />
                    )}
                  </Link>
                </td>
                <td className="border-t">
                  <Link
                    className="flex items-center px-6 py-4"
                    href={`/organizations/${id}/edit`}
                    tabIndex={-1}
                  >
                    {city}
                  </Link>
                </td>
                <td className="border-t">
                  <Link
                    className="flex items-center px-6 py-4"
                    href={`/organizations/${id}/edit`}
                    tabIndex={-1}
                  >
                    {phone}
                  </Link>
                </td>
                <td className="w-px border-t">
                  <Link
                    className="flex items-center px-4"
                    href={`/organizations/${id}/edit`}
                    tabIndex={-1}
                  >
                    <Icon
                      name="cheveron-right"
                      className="block w-6 h-6 fill-gray-400"
                    />
                  </Link>
                </td>
              </tr>
            ))}
            {data.length === 0 && (
              <tr>
                <td className="px-6 py-4 border-t" colSpan={4}>
                  No organizations found.
                </td>
              </tr>
            )}
          </tbody>
        </table>
      </div>
      <Pagination links={links} />
    </>
  )
}

Index.layout = withLayout(Layout)

export default Index
